#!/usr/bin/env bash
# Installing nginx on a remote server and configuring it

sudo apt update
sudo apt install nginx -y
sudo touch /var/www/html/index.html
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo service nginx start
